export type WorkshopMenuStatus =
  | 'implemented'
  | 'implemented-alias'
  | 'excluded-backlog'
  | 'unresolved'

export type WorkshopMenuEntry = {
  navigationId: string
  level1: string
  level2: string
  level3?: string
  navigationLabel: string
  processId?: string
  status: WorkshopMenuStatus
  searchAliases?: string[]
  notes?: string
}

export const WORKSHOP_MENU_CONFIG: WorkshopMenuEntry[] = [
  {
    navigationId: 'master-vendor',
    level1: '기준정보',
    level2: '기준정보',
    level3: '거래처',
    navigationLabel: '거래처',
    status: 'excluded-backlog',
    notes: '독립 Detail Process가 없어 live menu에서는 제외한다.',
  },
  {
    navigationId: 'master-item',
    level1: '기준정보',
    level2: '기준정보',
    level3: '품목',
    navigationLabel: '품목',
    status: 'excluded-backlog',
    notes: '독립 Detail Process가 없어 live menu에서는 제외한다.',
  },
  {
    navigationId: 'business-project',
    level1: '사업관리',
    level2: '프로젝트',
    navigationLabel: '프로젝트',
    processId: 'business-to-purchase-request',
    status: 'implemented-alias',
    searchAliases: ['사업기회', '계약', '프로젝트', '구매요청'],
  },
  {
    navigationId: 'business-general-operation',
    level1: '사업관리',
    level2: '일반운영',
    navigationLabel: '일반운영',
    status: 'excluded-backlog',
    notes: '일반 품의/발의 Process가 없어 live menu에서는 제외한다.',
  },
  {
    navigationId: 'purchase-project-goods',
    level1: '구매',
    level2: '프로젝트',
    level3: 'MD/응원봉/앨범',
    navigationLabel: 'MD/응원봉/앨범',
    processId: 'purchase-to-ap-invoice',
    status: 'implemented-alias',
    searchAliases: ['MD', '응원봉', '앨범', '수불상품', '프로젝트 구매'],
  },
  {
    navigationId: 'purchase-project-service',
    level1: '구매',
    level2: '프로젝트',
    level3: '공연/콘텐츠/플랫폼',
    navigationLabel: '공연/콘텐츠/플랫폼',
    processId: 'service-purchase-to-ap',
    status: 'implemented-alias',
    searchAliases: ['공연', '콘텐츠', '플랫폼', '서비스 구매'],
  },
  {
    navigationId: 'purchase-project-fnb',
    level1: '구매',
    level2: '프로젝트',
    level3: 'F&B',
    navigationLabel: 'F&B',
    processId: '구매-요청-매입-전표-생성-f-b',
    status: 'implemented',
    searchAliases: ['F&B', '식음료', '프로젝트 구매'],
  },
  {
    navigationId: 'purchase-project-import',
    level1: '구매',
    level2: '프로젝트',
    level3: '수입',
    navigationLabel: '수입',
    status: 'excluded-backlog',
    notes: '수입 구매 전용 Process가 없어 live menu에서는 제외한다.',
  },
  {
    navigationId: 'purchase-project-return',
    level1: '구매',
    level2: '프로젝트',
    level3: '구매반품',
    navigationLabel: '구매반품',
    processId: 'purchase-return',
    status: 'implemented',
    searchAliases: ['구매반품', '반품'],
  },
  {
    navigationId: 'purchase-general-rnd',
    level1: '구매',
    level2: '일반',
    level3: '연구개발',
    navigationLabel: '연구개발',
    status: 'excluded-backlog',
    notes: '독립 연구개발 구매 Process가 없어 live menu에서는 제외한다.',
  },
  {
    navigationId: 'purchase-general-hrga',
    level1: '구매',
    level2: '일반',
    level3: '인사총무',
    navigationLabel: '인사총무',
    processId: '구매-요청-매입전표-생성-인사총무',
    status: 'implemented',
    searchAliases: ['인사총무', '일반구매'],
  },
  {
    navigationId: 'purchase-general-it-sw',
    level1: '구매',
    level2: '일반',
    level3: 'IT/SW',
    navigationLabel: 'IT/SW',
    processId: '구매-요청-매입-전표-생성-it-s-w',
    status: 'implemented',
    searchAliases: ['IT', 'SW', 'S/W', '소프트웨어', '일반구매'],
  },
  {
    navigationId: 'sales-b2b',
    level1: '판매',
    level2: 'B2B',
    navigationLabel: 'B2B',
    processId: 'b2b-domestic-order-to-sales',
    status: 'implemented',
    searchAliases: ['B2B', '국내', '법인판매'],
  },
  {
    navigationId: 'sales-b2b-export',
    level1: '판매',
    level2: 'B2B 수출',
    navigationLabel: 'B2B 수출',
    processId: 'b2b-export-order-to-sales',
    status: 'implemented',
    searchAliases: ['B2B', '수출', '해외'],
  },
  {
    navigationId: 'sales-online',
    level1: '판매',
    level2: '온라인몰',
    navigationLabel: '온라인몰',
    processId: 'b2c-order-to-sales',
    status: 'implemented-alias',
    searchAliases: ['B2C', '온라인판매', '온라인몰', '카페24'],
  },
  {
    navigationId: 'sales-preorder',
    level1: '판매',
    level2: '예약판매',
    navigationLabel: '예약판매',
    processId: 'preorder-to-sales',
    status: 'implemented',
    searchAliases: ['예약판매', '선주문'],
  },
  {
    navigationId: 'sales-signing-event',
    level1: '판매',
    level2: '사인회',
    navigationLabel: '사인회',
    processId: 'event-sales',
    status: 'implemented-alias',
    searchAliases: ['사인회', '이벤트', '이벤트 판매'],
    notes: 'event-sales가 사인회만 의미하는지, 일반 이벤트 판매까지 포함하는지는 확인 필요.',
  },
  {
    navigationId: 'field-sales-concert-popup',
    level1: '판매',
    level2: '현장판매',
    level3: '공연/팝업',
    navigationLabel: '공연/팝업',
    processId: 'popup-concert-stock-sales-sync',
    status: 'implemented-alias',
    searchAliases: ['공연', '팝업', '현장판매'],
  },
  {
    navigationId: 'field-sales-store',
    level1: '판매',
    level2: '현장판매',
    level3: '매장',
    navigationLabel: '매장',
    processId: 'store-sales',
    status: 'implemented-alias',
    searchAliases: ['매장', 'POS', '현장판매'],
  },
  {
    navigationId: 'return-sales-b2b',
    level1: '반품',
    level2: '판매반품',
    level3: 'B2B',
    navigationLabel: 'B2B',
    processId: 'b2b-domestic-return',
    status: 'implemented',
    searchAliases: ['B2B 반품', '판매반품'],
  },
  {
    navigationId: 'return-sales-online',
    level1: '반품',
    level2: '판매반품',
    level3: '온라인몰',
    navigationLabel: '온라인몰',
    processId: 'b2c-return',
    status: 'implemented-alias',
    searchAliases: ['B2C 반품', '온라인몰 반품', '판매반품'],
  },
  {
    navigationId: 'return-purchase',
    level1: '반품',
    level2: '구매반품',
    navigationLabel: '구매반품',
    processId: 'purchase-return',
    status: 'implemented',
    searchAliases: ['구매반품', '반품'],
  },
  {
    navigationId: 'inventory-movement',
    level1: '재고',
    level2: '재고이동',
    navigationLabel: '재고이동',
    processId: 'stock-movement',
    status: 'implemented',
    searchAliases: ['재고이동', '이동'],
  },
  {
    navigationId: 'inventory-store-transfer',
    level1: '재고',
    level2: '매장간 이동',
    navigationLabel: '매장간 이동',
    processId: 'stock-transfer',
    status: 'implemented-alias',
    searchAliases: ['매장간 이동', '창고간 이동', '재고이동'],
    notes: 'Runtime title/variant는 창고간이지만 Workshop Navigation Label은 매장간 이동으로 표시한다.',
  },
  {
    navigationId: 'inventory-other-receipt',
    level1: '재고',
    level2: '기타입고',
    navigationLabel: '기타입고',
    processId: 'other-receipt',
    status: 'implemented',
    searchAliases: ['기타입고', '입고'],
  },
  {
    navigationId: 'inventory-other-issue',
    level1: '재고',
    level2: '기타출고',
    navigationLabel: '기타출고',
    processId: 'other-issue',
    status: 'implemented',
    searchAliases: ['기타출고', '출고', '타계정'],
  },
  {
    navigationId: 'settlement-royalty-agency',
    level1: '정산',
    level2: '로열티정산',
    level3: '기획사',
    navigationLabel: '기획사',
    processId: 'royalty-mg-settlement',
    status: 'implemented',
    searchAliases: ['로열티', 'MG', '기획사 정산'],
  },
  {
    navigationId: 'settlement-consignment-agency',
    level1: '정산',
    level2: '판매대행 정산',
    level3: '판매대행',
    navigationLabel: '판매대행',
    processId: 'consignment-settlement',
    status: 'implemented-alias',
    searchAliases: ['판매대행', '위탁', '위탁정산'],
    notes: '판매대행 정산과 위탁 매출 정산의 업무 범위 동일성은 확인 필요.',
  },
  {
    navigationId: 'settlement-revenue-share',
    level1: '정산',
    level2: '수익배분정산',
    level3: '매출·비용',
    navigationLabel: '매출·비용',
    processId: 'revenue-share-settlement',
    status: 'implemented',
    searchAliases: ['수익배분', '매출', '비용', '정산'],
  },
  {
    navigationId: 'settlement-project-service',
    level1: '정산',
    level2: '프로젝트정산',
    level3: '매출·비용',
    navigationLabel: '매출·비용',
    processId: 'service-project-settlement',
    status: 'implemented',
    searchAliases: ['프로젝트정산', '매출', '비용', '서비스 정산'],
  },
  {
    navigationId: 'sales-service-revenue',
    level1: '판매',
    level2: '서비스매출',
    navigationLabel: '서비스매출',
    processId: 'service-order-to-sales',
    status: 'unresolved',
    notes: 'v1 live menu에는 포함하지 않는다. 판매 > 서비스매출 후보로 검토한다.',
  },
  {
    navigationId: 'business-service-expense',
    level1: '사업관리',
    level2: '서비스 비용정산',
    navigationLabel: '서비스 비용정산',
    processId: 'service-business-to-expense',
    status: 'unresolved',
    notes: '사업관리 > 프로젝트 또는 일반운영 중 위치를 확정해야 한다.',
  },
  {
    navigationId: 'master-storage-location',
    level1: '기준정보',
    level2: '기준정보',
    level3: '저장위치',
    navigationLabel: '저장위치',
    processId: 'storage-location-master',
    status: 'unresolved',
    notes: '기준정보 > 저장위치 후보이나 현재 승인 메뉴에는 포함하지 않는다.',
  },
]
